# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Edit_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(416, 296)
        self.nameLabel = QtWidgets.QLabel(parent=Form)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.nameInput = QtWidgets.QLineEdit(parent=Form)
        self.nameInput.setGeometry(QtCore.QRect(130, 20, 113, 22))
        self.nameInput.setObjectName("nameInput")
        self.roastingLabel = QtWidgets.QLabel(parent=Form)
        self.roastingLabel.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.roastingLabel.setObjectName("roastingLabel")
        self.roastingInput = QtWidgets.QLineEdit(parent=Form)
        self.roastingInput.setGeometry(QtCore.QRect(130, 50, 113, 22))
        self.roastingInput.setObjectName("roastingInput")
        self.selectionLabel = QtWidgets.QLabel(parent=Form)
        self.selectionLabel.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.selectionLabel.setObjectName("selectionLabel")
        self.selectionSelect = QtWidgets.QComboBox(parent=Form)
        self.selectionSelect.setGeometry(QtCore.QRect(140, 80, 111, 22))
        self.selectionSelect.setObjectName("selectionSelect")
        self.selectionSelect.addItem("")
        self.selectionSelect.addItem("")
        self.descriptionLabel = QtWidgets.QLabel(parent=Form)
        self.descriptionLabel.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.priceLabel = QtWidgets.QLabel(parent=Form)
        self.priceLabel.setGeometry(QtCore.QRect(20, 180, 121, 16))
        self.priceLabel.setObjectName("priceLabel")
        self.priceInput = QtWidgets.QLineEdit(parent=Form)
        self.priceInput.setGeometry(QtCore.QRect(130, 180, 113, 22))
        self.priceInput.setObjectName("priceInput")
        self.valueLabel = QtWidgets.QLabel(parent=Form)
        self.valueLabel.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.valueLabel.setObjectName("valueLabel")
        self.valueInput = QtWidgets.QLineEdit(parent=Form)
        self.valueInput.setGeometry(QtCore.QRect(130, 210, 113, 22))
        self.valueInput.setObjectName("valueInput")
        self.saveButton = QtWidgets.QPushButton(parent=Form)
        self.saveButton.setGeometry(QtCore.QRect(270, 250, 131, 28))
        self.saveButton.setObjectName("saveButton")
        self.textLabel = QtWidgets.QLabel(parent=Form)
        self.textLabel.setGeometry(QtCore.QRect(20, 260, 241, 16))
        self.textLabel.setText("")
        self.textLabel.setObjectName("textLabel")
        self.descriptionInput = QtWidgets.QTextEdit(parent=Form)
        self.descriptionInput.setGeometry(QtCore.QRect(130, 110, 261, 61))
        self.descriptionInput.setObjectName("descriptionInput")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLabel.setText(_translate("Form", "Название сорта"))
        self.roastingLabel.setText(_translate("Form", "Степень обжарки"))
        self.selectionLabel.setText(_translate("Form", "Молотый/в зёрнах"))
        self.selectionSelect.setItemText(0, _translate("Form", "Молотый"))
        self.selectionSelect.setItemText(1, _translate("Form", "В зёрнах"))
        self.descriptionLabel.setText(_translate("Form", "Описание вкуса"))
        self.priceLabel.setText(_translate("Form", "Цена"))
        self.valueLabel.setText(_translate("Form", "Объём упаковки"))
        self.saveButton.setText(_translate("Form", "Сохранить"))
